      *================================================================*
      * DCLCLAIM - DCLGEN OUTPUT FOR DB2 TABLE CLAIM                  *
      *                                                                *
      * GENERATED BY DCLGEN. MAPS THE DB2 CLAIM TABLE COLUMNS TO HOST  *
      * VARIABLES USED BY THE ONLINE PROGRAMS' EMBEDDED SQL. NOTE THE  *
      * HOST-VARIABLE LAYOUT MIRRORS COPYBOOK CLAIMREC BUT USES DB2    *
      * NULL INDICATORS AND VARCHAR-STYLE TYPES.                       *
      *================================================================*
      ******************************************************************
      * DCLGEN TABLE(CLAIM)                                            *
      *        LIBRARY(OEM.INCENT.DCLGEN(DCLCLAIM))                    *
      *        QUOTE                                                   *
      * ... IS THE DCLGEN COMMAND THAT MADE THE FOLLOWING STATEMENTS   *
      ******************************************************************
           EXEC SQL DECLARE CLAIM TABLE
           ( CLAIM_ID                       CHAR(10) NOT NULL,
             VIN                            CHAR(17) NOT NULL,
             DEALER_ID                      CHAR(6) NOT NULL,
             PROGRAM_ID                     CHAR(6) NOT NULL,
             SALE_DATE                      DATE NOT NULL,
             SALE_PRICE                     DECIMAL(9, 2) NOT NULL,
             CLAIM_TYPE                     CHAR(8) NOT NULL,
             PRIOR_OWN                      CHAR(1) NOT NULL,
             CUST_BANK                      CHAR(1) NOT NULL
           ) END-EXEC.
      ******************************************************************
      * COBOL DECLARATION FOR TABLE CLAIM                             *
      ******************************************************************
       01  DCLCLAIM.
           10 CLAIM-ID             PIC X(10).
           10 VIN                  PIC X(17).
           10 DEALER-ID            PIC X(6).
           10 PROGRAM-ID           PIC X(6).
           10 SALE-DATE            PIC X(10).
           10 SALE-PRICE           PIC S9(7)V99 USAGE COMP-3.
           10 CLAIM-TYPE           PIC X(8).
           10 PRIOR-OWN            PIC X(1).
           10 CUST-BANK            PIC X(1).
      ******************************************************************
      * THE NUMBER OF COLUMNS DESCRIBED BY THIS DECLARATION IS 9      *
      ******************************************************************
