#!/usr/bin/env bash
# Run the modernized Spring Boot service over the same test fixtures used by
# the legacy COBOL batch and emit a payout register for equivalence comparison.
#
# Usage:  ./modernized/equivalence/run_modern.sh
#
# Prerequisites:
#   - Java 17+ and Maven on PATH
#   - testdata/input/*.dat present (generated by harness/make_fixtures.py)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SERVICE="$ROOT/modernized/service"
EQUIV="$ROOT/modernized/equivalence"
INPUT="$ROOT/testdata/input"
OUT_DIR="${1:-$ROOT/build/out}"
PORT=8081

mkdir -p "$OUT_DIR"

# 1. Build the service (skip if jar already exists)
JAR="$SERVICE/target/incentive-service-0.1.0-SNAPSHOT.jar"
if [[ ! -f "$JAR" ]]; then
    echo "==> building Spring Boot service"
    mvn -f "$SERVICE/pom.xml" -q package -DskipTests
fi

# 2. Start the service
echo "==> starting incentive service on port $PORT"
DEALERS_FILE="$INPUT/dealers.dat" \
PROGRAMS_FILE="$INPUT/programs.dat" \
java -jar "$JAR" --server.port="$PORT" &>/dev/null &
SVC_PID=$!
trap 'kill $SVC_PID 2>/dev/null || true' EXIT

# 3. Wait for readiness
echo "==> waiting for service"
for i in $(seq 1 30); do
    if curl -sf "http://localhost:$PORT/api/claims/process" -X POST \
         -H 'Content-Type: application/json' \
         -d '{"claimId":"PING","vin":"X","dealerId":"X","programId":"X","saleDate":0,"salePrice":0,"claimType":"X","priorOwn":false,"custBank":false}' \
         >/dev/null 2>&1; then
        break
    fi
    sleep 1
done

# 4. Reset any prior state
curl -sf -X DELETE "http://localhost:$PORT/api/claims/state" >/dev/null 2>&1 || true

# 5. Drive claims through the service
echo "==> processing claims"
python3 "$EQUIV/driver.py" "$INPUT/claims.dat" "$OUT_DIR/modern_payout.dat" \
        "http://localhost:$PORT"

echo "==> modern payout register written to $OUT_DIR/modern_payout.dat"
